services:
  backend:
    build:
      context: ./src/dotnet/VectorEmbeddingService
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  pipeline:
    build:
      context: .
      dockerfile: production/dockerfile
    container_name: pipeline
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      API_URL: http://backend:5000
    entrypoint: ["sleep", "infinity"]

    volumes:
      - ./src:/app/src
      - ./production:/app/production
      - ./data:/app/data

  xpodashboard:
    image: node:20-alpine
    container_name: xpodashboard
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./src/xpodashboard:/app
    command: sh -c "npm install && npm run dev"
