FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
COPY scrapy.cfg .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your code
COPY src/ ./src/
COPY production/run_pipeline.sh ./run_pipeline.sh

RUN chmod +x ./run_pipeline.sh

CMD ["./run_pipeline.sh"]