FROM node:20-alpine

WORKDIR /app

COPY src/xpodashboard/package*.json ./

RUN npm install

COPY src/xpodashboard/. .

# Set environment variables
ENV NEXT_PUBLIC_API_URL=http://localhost:5000

EXPOSE 3000

CMD ["npm", "run","dev"]
