name: Trigger auto deployment for pipeline

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/pipeline-AutoDeployTrigger-b66e4e89-5f39-4b80-82f8-c2716b015471.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PIPELINE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PIPELINE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PIPELINE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: xpoaichatbotacr.azurecr.io
          registryUsername: ${{ secrets.PIPELINE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PIPELINE_REGISTRY_PASSWORD }}
          containerAppName: pipeline
          resourceGroup: Xpo-AI-Chatbot
          imageToBuild: xpoaichatbotacr.azurecr.io/pipeline:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


