name: Run Pipeline Weekly

on:
  schedule:
    - cron: '0 22 * * 6' # Every Saturday at 22:00 UTC (adjust as needed)
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start Pipeline Container
        run: |
          az containerapp job start --name pipeline --resource-group Xpo-AI-Chatbot