import type { Metadata } from "next";
import { Ropa_Sans, Open_Sans } from "next/font/google";
import "./globals.css";

const ropasans = Ropa_Sans({
  subsets: ["latin"],
  weight: "400",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ropasans.className} ${openSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
